[package]
name = "att_system"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.0", features = ["uuid", "chrono"] }
diesel-async = { version = "0.7.0", features = ["postgres", "bb8"] }
uuid = { version = "1.20.0", features = ["v7", "serde"]}
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "fs", "io-util"] }
axum = { version = "0.8.8", features = ["multipart", "ws"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.13.2", default-features = false, features = ["json", "rustls-tls"] }
log = "0.4.29"
env_logger = "0.11.9"
jwt-simple = { version = "0.12.14", default-features = false, features = ["pure-rust"] }
rust-embed ="8.11.0"
mime_guess = "2.0.5"
tower-http = { version = "0.6.2", features = ["cors"] }
tokio-stream = "0.1"
