[package]
name = "att_system"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.0", features = ["uuid"] }
diesel-async = { version = "0.7.0", features = ["postgres", "bb8"] }
uuid = { version = "1.20.0", features = ["v7", "serde"]}
dotenvy = "0.15"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "fs", "io-util"] }
axum = { version = "0.8.8", features = ["multipart"] }
serde = { version = "1.0.228", features = ["derive"] }
reqwest = { version = "0.13.2", features = ["json"]}
log = "0.4.29"
env_logger = "0.11.9"
jwt-simple = "0.12.14"
rust-embed="8.11.0"
mime_guess = "2.0.5"
tower-http = { version = "0.6.6", features = ["cors"] }
